# -*- coding: utf-8 -*-
"""api_stockout.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vr_3iJK_pKLEYikX1xpIQ0aFfDMq_sDu
"""

from fastapi import FastAPI
from pydantic import BaseModel
import joblib
import numpy as np

# Initialize API
app = FastAPI()

# Load the model
model = joblib.load("best_model_random_forest.pkl")

# Define input schema
class StockoutRequest(BaseModel):
    product_id_encoded: int
    demand: float
    demand_7d_avg: float
    remaining_inventory: float


@app.post("/predict")
def predict(request: StockoutRequest):
    features = np.array([[request.product_id_encoded, request.demand, request.demand_7d_avg, request.remaining_inventory]])
    prediction = model.predict(features)[0]
    probability = model.predict_proba(features)[0][1]
    return {
        "stockout_prediction": int(prediction),
        "stockout_probability": round(probability, 2)
    }

@app.get("/")
def root():
    return {"message": "Welcome to the Stockout API. Visit /docs for Swagger
