# -*- coding: utf-8 -*-
"""api_stockout.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vr_3iJK_pKLEYikX1xpIQ0aFfDMq_sDu
"""

from fastapi import FastAPI
from pydantic import BaseModel
import joblib
import numpy as np

# Load the model
model = joblib.load("best_model_random_forest.pkl")

# Define input schema
class StockoutRequest(BaseModel):
    product_id_encoded: int
    demand: float
    demand_7d_avg: float
    remaining_inventory: float

# Initialize API
app = FastAPI()

@app.post("/predict")
def predict_stockout(data: StockoutRequest):
    X = np.array([[data.demand, data.demand_7d_avg, data.remaining_inventory, data.product_id_encoded]])
    prediction = model.predict(X)[0]
    probability = model.predict_proba(X)[0][1]  # probability of stockout
    return {
        "stockout_prediction": int(prediction),
        "stockout_probability": round(probability, 4)
    }